
package cliente.ArchivosGUI;

import cliente.NotificacionClienteInt;
import sensor.dto.Sensor;

/**
 *
 * @authors Alejandro Muñoz - Cristian Collazos
 */
public class GUINotificacion extends javax.swing.JFrame implements NotificacionClienteInt{

    /**
     * Creates new form GUIAdministrador
     */
    public GUINotificacion() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTexto1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        n1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelTexto2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        panelTexto.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Alertas");

        javax.swing.GroupLayout panelTextoLayout = new javax.swing.GroupLayout(panelTexto);
        panelTexto.setLayout(panelTextoLayout);
        panelTextoLayout.setHorizontalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTextoLayout.setVerticalGroup(
            panelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTexto1.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea3.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        n1.setBackground(new java.awt.Color(255, 51, 51));
        n1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Indicadores fuera de rango");

        javax.swing.GroupLayout panelTexto1Layout = new javax.swing.GroupLayout(panelTexto1);
        panelTexto1.setLayout(panelTexto1Layout);
        panelTexto1Layout.setHorizontalGroup(
            panelTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTexto1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel5)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(panelTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panelTexto1Layout.setVerticalGroup(
            panelTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(n1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTexto2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Desarrollado por: Alejandro Muñoz - Cristian Collazos");

        javax.swing.GroupLayout panelTexto2Layout = new javax.swing.GroupLayout(panelTexto2);
        panelTexto2.setLayout(panelTexto2Layout);
        panelTexto2Layout.setHorizontalGroup(
            panelTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTexto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTexto2Layout.setVerticalGroup(
            panelTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTexto2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINotificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel n1;
    private javax.swing.JPanel panelTexto;
    private javax.swing.JPanel panelTexto1;
    private javax.swing.JPanel panelTexto2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notificar(Sensor objSensor) {
          jTextArea3.setText("");
          EvaluarSensor(objSensor);
    }
    
    private void EvaluarSensor(Sensor objSensor){
        int cant = 0;
        if(objSensor.getIndicadores().getFrecuenciaCardiaca() < 60 || objSensor.getIndicadores().getFrecuenciaCardiaca() > 80){
            cant++;
            jTextArea3.append("\nFrecuencia Cardiaca: "+ objSensor.getIndicadores().getFrecuenciaCardiaca()+"\n");
        }
        if(objSensor.getIndicadores().getPresionSistolica() < 110 || objSensor.getIndicadores().getPresionSistolica() > 140){
            cant++;
            jTextArea3.append("\nPresion Sistolica: "+ objSensor.getIndicadores().getPresionSistolica()+"\n");
        }
        if(objSensor.getIndicadores().getPresionDiastolica() < 70 || objSensor.getIndicadores().getPresionDiastolica() > 90){
            cant++;
            jTextArea3.append("\nPresion Diastolica: "+ objSensor.getIndicadores().getPresionDiastolica()+"\n");
        }
        if(objSensor.getIndicadores().getFrecuenciaRespiratoria() < 12 || objSensor.getIndicadores().getFrecuenciaRespiratoria() > 20){
            cant++;
            jTextArea3.append("\nFrecuencia Respiratoria: "+ objSensor.getIndicadores().getFrecuenciaRespiratoria()+"\n");
        }
        if(objSensor.getIndicadores().getTemperatura() < 36 || objSensor.getIndicadores().getTemperatura() > 37){
            cant++;
            jTextArea3.append("\nTemperatura: "+ objSensor.getIndicadores().getTemperatura()+"\n");
        }
        if(objSensor.getIndicadores().getOxigeno() < 95 || objSensor.getIndicadores().getOxigeno() > 100){
            cant++;
            jTextArea3.append("\nOxigeno: "+ objSensor.getIndicadores().getOxigeno()+"\n");
        }
        n1.setText("El paciente en la habitacion #"+objSensor.getId()+" presenta "+cant+" indicadores fuera de rango");
        
    }
}
